name: Lint Workflows

on:
  pull_request:
    paths:
    - '.github/**.yml'
    - '.github/**.yaml'

jobs:
  lintYaml:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Checkout github-config
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        repository: paketo-buildpacks/github-config
        path: github-config

    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
      with:
        python-version: 3.8

    - name: Install yamllint
      run: pip install yamllint

    - name: Lint YAML files
      run: yamllint ./.github -c github-config/.github/.yamllint
