name: Synchronize Labels
"on":
    push:
        branches:
            - main
        paths:
            - .github/labels.yml
    workflow_dispatch: {}
jobs:
    synchronize:
        name: Synchronize Labels
        runs-on:
            - ubuntu-22.04
        steps:
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
            - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
