name: Test Builder

on:
  workflow_dispatch: {}

jobs:

  smoke:
    name: Smoke Test
    runs-on: ubuntu-22.04
    steps:
    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
      with:
        go-version: 'stable'

    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Run Smoke Tests
      run: ./scripts/smoke.sh
